SELECT * FROM KOPO_PRODUCT_VOLUME
 WHERE 1=1
   AND PRODUCTGROUP = 'ST0002'
   AND YEARWEEK IN('201415','201516');
   
SELECT * FROM KOPO_PRODUCT_VOLUME
 WHERE 1=1
   AND PRODUCTGROUP = 'ST0002'
   AND YEARWEEK>201514
   AND YEARWEEK<201517;
   
SELECT * FROM KOPO_PRODUCT_VOLUME
 WHERE 1=1
   AND PRODUCTGROUP = 'ST0002'
   AND (YEARWEEK = '201515' OR YEARWEEK = '201516');
   
   
  
SELECT REGIONID, ITEM, TARGETWEEK, PLANWEEK, MAP_PRICE, IR, PMAP, PRODUCT, ROUND(PMAP*0.9,0) AS PMAP_DISCOUNT
  FROM KOPO_PROMOTION;
  
SELECT REGIONID, ITEM, TARGETWEEK, PLANWEEK, MAP_PRICE, IR, PMAP, PRODUCT, ROUND(PMAP-(PMAP*0.1),1) AS PMAP_DISCOUNT
  FROM KOPO_PROMOTION;
  
  
  
SELECT 
  CASE WHEN MAP_PRICE = 0
            THEN 1
       WHEN MAP_PRICE = 1
            THEN 2
       ELSE PMAP/NVL (MAP_PRICE, 1) END AS PROMOTION_RATIO
  FROM KOPO_PROMOTION;
  
  
SELECT * FROM KOPO_PRODUCT_VOLUME
 WHERE 1=1
   AND YEARWEEK IN('201515','201517','201519');
   
SELECT * FROM TABS
 WHERE TABLE_NAME LIKE '%MST%';