SELECT 
    LPAD(WEEK,2,'0') AS WEEK
    ,QTY
FROM SORT_EXAMPLE
ORDER BY LPAD(WEEK,2,'0');



SELECT 
    LPAD(WEEK,2,'0') AS WEEK
    ,QTY
FROM SORT_EXAMPLE
ORDER BY TO_NUMBER(WEEK);



SELECT CUSTOMERCODE
    ,LPAD(CUSTOMERCODE,10,'0')
    ,SUBSTR(LPAD(CUSTOMERCODE,10,'0'),-4)
    ,REPLACE (LPAD(CUSTOMERCODE,10,'0')
            ,SUBSTR(LPAD(CUSTOMERCODE,10,'0'),-4)
            ,'****')
FROM KOPO_CUSTOMERDATA;
  


SELECT 
    FIRST_NUMBER
    , SECOND_NUMBER
    , FIRST_NUMBER/SECOND_NUMBER AS AVG
    , ROUND(FIRST_NUMBER/SECOND_NUMBER,2) AS ROUND_EX
    , CEIL(FIRST_NUMBER/SECOND_NUMBER) AS CEIL_EX
    , FLOOR(FIRST_NUMBER/SECOND_NUMBER) AS FLOOR_EX
    , MOD(FIRST_NUMBER, SECOND_NUMBER) AS MOD_EX
    , POWER(FIRST_NUMBER, SECOND_NUMBER) AS POW_EX
FROM NUMBER_EXAMPLE ;

--ACCURACY =1 ? ABS(예측값-실제값) / 예측값 공식
SELECT 
    YEARWEEK
    ,ACTUAL
    ,FCST
    ,ROUND((1-ABS(FCST-ACTUAL)/FCST)*100, 2) AS ACCURACY
FROM RMSE_MAE_EXAMPLE2;


SELECT *
FROM(
SELECT 
    YEARWEEK
    ,ACTUAL
    ,FCST
    ,ROUND((1-ABS(FCST-ACTUAL)/FCST)*100, 2) AS ACCURACY
FROM RMSE_MAE_EXAMPLE2
)WHERE 1=1 AND ACCURACY < 50;



SELECT
    SYSDATE
    , NEXT_DAY(SYSDATE,2)
    , LAST_DAY(SYSDATE)
FROM DUAL;


SELECT TO_CHAR(SYSDATE, 'YYYYMMDD')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY MONDD')||'일'
FROM DUAL;

--일주일 전-- 
SELECT TO_CHAR(SYSDATE-7, 'YYYYMMDD')
FROM DUAL; 




SELECT 
    YEARWEEK,
    CASE WHEN QTY<1000 THEN 1000
         WHEN QTY>1000 AND QTY <10000 THEN 10000
         ELSE 30000 END AS QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW


