CREATE TABLE RMSE_MAE_ST_JKH AS
SELECT 
   ROUND((1-ABS(FCST-ACTUAL)/FCST)*100, 2) AS ACCURACY
FROM RMSE_MAE_EXAMPLE2;

SELECT * FROM CUSTOMERDATA;


SELECT A.*,
    CASE WHEN SUBSTR(CUSTID,1,1)='A' THEN 1
         WHEN SUBSTR(CUSTID,1,1)='B' THEN 0
         WHEN SUBSTR(CUSTID,1,1)='C' THEN 2
         ELSE 3 END AS NUM
         FROM CUSTOMERDATA A
         ORDER BY NUM;
         
         
         
         
         
SELECT A.*
       , DECODE(A.GENDER,'Male',1,'Female',2,0) AS SORT_ORDER
       FROM KOPO_CUSTOMERDATA A
WHERE 1=1
ORDER BY SORT_ORDER;


SELECT * FROM KOPO_CUSTOMERDATA ;
SELECT * FROM DT_RESULT_FINAL3;

SELECT A.*
       ,DECODE(A.PREDICTION_QTY,'0',0
               ,ROUND((1-ABS(PREDICTION_QTY-REAL_QTY)/PREDICTION_QTY)*100, 2)) AS ACCURACY
FROM DT_RESULT_FINAL3 A;


SELECT REGIONID, AVG(QTY) FROM KOPO_CHANNEL_SEASONALITY_NEW
GROUP BY REGIONID
ORDER BY REGIONID;

SELECT
    REGIONID,
    PRODUCT,
    AVG(QTY)
FROM KOPO_CHANNEL_SEASONALITY_NEW 
GROUP BY REGIONID, PRODUCT
ORDER BY REGIONID, PRODUCT;


SELECT 
    REGIONID,
    PRODUCT,
    AVG(QTY)
FROM KOPO_CHANNEL_SEASONALITY_NEW
WHERE REGIONID = 'A01'
GROUP BY REGIONID, PRODUCT
HAVING AVG(QTY) > 2000;


SELECT * FROM RMSE_MAE_EXAMPLE;




SELECT
    ITEM,
    SQRT(AVG(POWER(ABS(PREDICTION-QTY),2))) AS RMSE
FROM RMSE_MAE_EXAMPLE 
GROUP BY ITEM;


SELECT 
    ITEM,
    AVG(ERROR),
    AVG(ERROR_POW),
    SQRT(AVG(ERROR_POW))
    FROM
    (
        SELECT 
            ITEM,
            YEARWEEK,
            QTY,
            PREDICTION,
            ABS(QTY-PREDICTION) AS ERROR,
            POWER(ABS(QTY-PREDICTION),2) AS ERROR_POW
        FROM RMSE_MAE_EXAMPLE
    )
GROUP BY ITEM;