select *from DT_RESULT_FINAL2;


SELECT * FROM (
    SELECT * FROM DT_RESULT_FINAL2
) 
PIVOT(
    SUM(SALES)
    FOR MEASURE IN
    ('REAL-QTY' AS REAL_QTY, 'PREDICTION-QTY' AS PREDICTION_QTY)
    )
ORDER BY PRODUCTGROUP,PRODUCT, ITEM, YEARWEEK;


SELECT 
    *
     FROM (
        SELECT REGIONID,PRODUCT,WEEK, AVG(QTY) AS AVG_QTY
        FROM KOPO_CHANNEL_SEASONALITY
        GROUP BY REGIONID,PRODUCT,WEEK
)
PIVOT( 
    SUM(AVG_QTY)
    FOR WEEK IN 
   ('1','2','3','4')
);

SELECT 
    *
     FROM (
        SELECT REGIONID,PRODUCT,WEEK, QTY
        FROM KOPO_CHANNEL_SEASONALITY
)
PIVOT( 
    SUM(QTY)
    FOR WEEK IN 
   ('1','2','3','4')
)


A02	SBS	614	558	551	548




ORDER BY PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK


SELECT 
    *
     FROM (
        SELECT  *
        FROM DT_RESULT_FINAL2
)
PIVOT( 
    SUM(SALES)
    FOR MEASURE IN 
   ('REAL-QTY' AS REAL_QTY,'PREDICTION-QTY' AS PREDICTION_QTY)
)
ORDER BY PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK



SELECT REGIONID, PRODUCT,ROUND(AVG(QTY),0) AS AVG_QTY, SUBSTR(YEARWEEK,5,6) AS WEEK
     FROM KOPO_CHANNEL_SEASONALITY_NEW
     GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6)


SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW


SELECT REGIONID, WEEK, ROUND(AVG(QTY),0) AS AVG_QTY
     FROM KOPO_CHANNEL_SEASONALITY
     GROUP BY REGIONID, WEEK


SELECT * FROM 
    (
     SELECT REGIONID, WEEK, ROUND(AVG(QTY),0) AS AVG_QTY
     FROM KOPO_CHANNEL_SEASONALITY
     GROUP BY REGIONID, WEEK)
PIVOT(
    AVG(AVG_QTY)
    FOR  WEEK IN ('1')
)

SELECT * FROM 
    (
     SELECT REGIONID, WEEK, ROUND(AVG(QTY),0) AS AVG_QTY
     FROM KOPO_CHANNEL_SEASONALITY
     GROUP BY REGIONID, WEEK)
PIVOT(
    AVG(AVG_QTY)
    FOR  WEEK IN ('1')
)



SELECT* FROM 
    (
    SELECT REGIONID, PRODUCT, ROUND(AVG(QTY),0) AS AVG_QTY
     FROM KOPO_CHANNEL_SEASONALITY_NEW
     GROUP BY REGIONID, PRODUCT)
PIVOT(
    AVG(AVG_QTY)
    FOR 
)

SELECT REGIONID, PRODUCT, WEEK, QTY 
    FROM KOPO_CHANNEL_SEASONALITY
    WHERE 1=1
    AND REGIONID = 'A02'
    AND PRODUCT ='SBS'
    AND WEEK = 1


SELECT * FROM 
(
    SELECT REGIONID, PRODUCT, WEEK, AVG(QTY) AS AVG_QTY 
    FROM KOPO_CHANNEL_SEASONALITY
    GROUP BY REGIONID, PRODUCT, WEEK
)PIVOT( SUM(AVG_QTY) FOR WEEK IN ('1','2'))


SELECT * FROM 
(
    SELECT REGIONID, PRODUCT, WEEK, QTY 
    FROM KOPO_CHANNEL_SEASONALITY
)PIVOT( AVG(QTY) FOR WEEK IN ('1','2'))


	SBS	614	558

A02	SBS	204.666666666667	186


SELECT * 
FROM (SELECT 
        REGIONID
        , PRODUCT
        , SUBSTR(YEARWEEK,5,6) AS WEEK
        , ROUND(AVG(QTY),0) AS AVG_QTY 
      FROM KOPO_CHANNEL_SEASONALITY_NEW
      GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6)
      ORDER BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6))
PIVOT(
    SUM(AVG_QTY)
    FOR WEEK IN('01' W01,'02' W02,'03' W03,'04' W04, '05' W05,'06' W06,'07' W07,'08' W08,'09' W09)
    )
ORDER BY REGIONID, PRODUCT;