SELECT * FROM KOPO_CHANNEL_SEASONALITY_FINAL;



--------1번문제[기본조회]--------
CREATE TABLE KOPO_ST_정경화_FINAL1 AS
SELECT * 
FROM KOPO_CHANNEL_SEASONALITY_FINAL
WHERE 1=1
  AND SUBSTR(YEARWEEK,5,2) != 53
  AND SUBSTR(YEARWEEK,1,4) >= 2015
  AND PRODUCT IN ('PRODUCT1','PRODUCT2');
  

--------2번문제[GROUPBY]--------
CREATE TABLE KOPO_ST_정경화_FINAL2 AS
SELECT REGIONID, PRODUCT, ROUND(AVG(QTY),0) AS AVG_QTY 
FROM KOPO_ST_정경화_FINAL1
GROUP BY REGIONID, PRODUCT;


--------3번문제[JOIN]--------
CREATE TABLE KOPO_ST_정경화_FINAL3 AS
SELECT A.REGIONID, A.PRODUCT, A.YEARWEEK, A.QTY, B.AVG_QTY 
  FROM KOPO_ST_정경화_FINAL1 A
LEFT JOIN KOPO_ST_정경화_FINAL2 B
ON A.REGIONID=B.REGIONID 
AND A.PRODUCT=B.PRODUCT;


--------4번문제[단일행함수]--------
CREATE TABLE KOPO_ST_정경화_FINAL4 AS
SELECT 
    A.*
    , ROUND((QTY/AVG_QTY),2) AS RATIO
FROM KOPO_ST_정경화_FINAL3 A;


--------5번문제[GROUPBY]--------
CREATE TABLE KOPO_ST_정경화_FINAL5 AS
SELECT 
    REGIONID
    , PRODUCT
    , SUBSTR(YEARWEEK, 5,6) AS WEEK
    , ROUND(AVG(RATIO),2) AS RATIO
FROM KOPO_ST_정경화_FINAL4
GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6);


--------6번문제[PIVOT]--------
CREATE TABLE KOPO_ST_정경화_FINAL6 AS
SELECT *
FROM (SELECT *
       FROM KOPO_ST_정경화_FINAL5)
PIVOT(
    SUM(RATIO)
    FOR WEEK IN('01'W01,'02'W02,'03'W03,'04'W04,'05'W05,'06'W06,'07'W07,'08'W08,'09'W09,'10'W10));



