
----사용자 조건 입력받기
SELECT
   REGIONID
   , PRODUCTGROUP
   , YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = &PRODUCT
OR YEARWEEK = '201544';


----정렬하기
SELECT
   REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
AND YEARWEEK BETWEEN 201501 AND 201503
ORDER BY YEARWEEK DESC;


----정렬 순서 지정하기
----LOWER (소문자변환) UPPER (대문자 변환)
SELECT A.*,
       CASE WHEN LOWER(A.GENDER) = 'not available'
            THEN 0
            WHEN UPPER(A.GENDER) = 'MALE'
            THEN 1
            ELSE 2 END AS SORT_ORDER
FROM KOPO_CUSTOMERDATA A
ORDER BY SORT_ORDER;


----차집합(MINUS)
SELECT YEARWEEK
  FROM KOPO_PRODUCT_VOLUME
 WHERE 1=1
   AND PRODUCTGROUP='ST0001'
 MINUS
SELECT YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
   AND YEARWEEK BETWEEN 201501 AND 201553;



----차집합 이렇게도 가능
SELECT YEARWEEK
 FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
 AND PRODUCTGROUP='ST0001'
 AND YEARWEEK NOT IN (
                      SELECT DISTINCT YEARWEEK
                        FROM KOPO_PRODUCT_VOLUME
                       WHERE YEARWEEK BETWEEN 201501 AND 201553
                      );



-----대/소문자 변경
SELECT 
   UPPER(PRODUCT) AS CASE1,
   LOWER(PRODUCT) AS CASE2
FROM KOPO_CHANNEL_SEASONALITY_NEW;


SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW
 WHERE 1=1
   AND LOWER(REGIONID) = LOWER(&UI_INPUT1)
   AND LOWER(PRODUCT) = LOWER(&UI_INPUT2);



----컬럼값 합치기
SELECT 
    CONCAT(REGIONID,CONCAT('_',PRODUCT)) AS KEYCOL1,
    REGIONID||'_'||PRODUCT AS KEYCOL2
FROM KOPO_CHANNEL_SEASONALITY_NEW;


----컬럼값 추출하기
SELECT substr('201642',0,4) FROM dual;


SELECT UPPER('asddxcDDDDss') FROM dual;



----컬럼값 채우기
SELECT 
LPAD(PRODUCTGROUP, 10, ‘0’)
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT LPAD('UN42F6000',13,0) FROM DUAL;


