SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
RIGHT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;



--1. Left Join (1)--
SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
LEFT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;


--1. Left Join (2)--
SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A, KOPO_REGION_MST B
WHERE 1=1
AND A.REGIONID=B.REGIONID(+);


--2. Inner Join (1)--
SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
INNER JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;

--2. Inner Join (2)--
SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A, KOPO_REGION_MST B
WHERE 1=1
AND A.REGIONID=B.REGIONID;




select count(*) 
  from kopo_channel_seasonality_new